[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "finpy"
version = "0.1.0"
description = "FinPy-Engine"
readme = "README.md"
authors = [{name = "aymank2020"}]
requires-python = ">=3.10"
license = { file = "LICENSE" }

[project.scripts]
finpy = "finpy.cli.main:main"

[project.optional-dependencies]
dev = ["pytest>=8.3", "pytest-cov>=5", "hypothesis>=6.112", "PyYAML>=6"]

[tool.setuptools.packages.find]
where = ["src"]
